<a href="https://colab.research.google.com/github/ragusurya/task7/blob/main/DataPreprocessing_Assignment11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#Data.csv

**Step 1: Importing the libraries**

In [5]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score



**Step 2: Importing dataset**

In [6]:
df=pd.read_csv("Data.csv")
df


Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

**Step 3: Handling the missing data**

In [7]:
X = df.iloc[:,:-1].values   # Independent variable --> Country, Age, Salary
y = df.iloc[:,-1].values    # Dependent variable   --> Purchased

In [8]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean', verbose = 0)           # Imputer object
imputer = imputer.fit(X[:,1:3])                                                     # compute(fit) the value to replace with
X[:,1:3] = imputer.transform(X[:,1:3])                                                 # replace(transform) with the fitted value 
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [9]:
#little bit confused about the statement missing data means df.isnull option gives the missing data.Laterlly i know imputer function so i mentioned above 

In [10]:
df.isnull()

Country    Age  Salary  Purchased
0    False  False   False      False
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False    True      False
5    False  False   False      False
6    False   True   False      False
7    False  False   False      False
8    False  False   False      False
9    False  False   False      False

In [11]:
df["Age"].fillna("not mention",inplace=True)
df
df["Salary"].fillna("not mention",inplace=True)
df


Country          Age       Salary Purchased
0   France         44.0      72000.0        No
1    Spain         27.0      48000.0       Yes
2  Germany         30.0      54000.0        No
3    Spain         38.0      61000.0        No
4  Germany         40.0  not mention       Yes
5   France         35.0      58000.0       Yes
6    Spain  not mention      52000.0        No
7   France         48.0      79000.0       Yes
8  Germany         50.0      83000.0        No
9   France         37.0      67000.0       Yes

**Step 4: Encoding categorical data**

In [12]:
from sklearn.preprocessing import LabelEncoder

labelencoder_X = LabelEncoder()                         # LabelEncoder object
X[:,0] = labelencoder_X.fit_transform(X[:,0])           # fit and tranform the categorical variable - Country

X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

**Step 5: Creating a dummy variable**

In [13]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer


# categorical_features = [0] indicates the index of the column 
# that is to be onehot encoded
#the new version does not accept the categorical features so that i use column tranform
ct = ColumnTransformer([("Country", OneHotEncoder(), [0])], remainder = 'passthrough')
X = ct.fit_transform(X)
X


array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [14]:
labelencoder_Y = LabelEncoder()                   # LabelEncoder object
y = labelencoder_Y.fit_transform(y)               # fit and tranform the categorical variable - Purchased

y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

**Step 6: Splitting the datasets into training sets and Test sets**

In [15]:
from sklearn.model_selection import train_test_split

# test_size = 0.2, indicates that 20% of the dataset will be used as test data and 80% as training data
# 'X_train, X_test, Y_train, Y_test', the order of specifying the train and test variables is very important
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

X_train

array([[0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

**Step 7: Feature Scaling**

In [16]:
from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()                   # StandardScaler object

# fit --> compute the mean(m) and standard deviation(sd) from the training data.
# transform --> use the computed m and sd values to scale/ standardize the training data
X_train = sc_X.fit_transform(X_train)     

# Note: the test data is only tranformed but NOT fitted
# tranform --> use the same m and sd values computed from training data to scale/ standardize the testing data

print(X_train)


[[-1.          2.64575131 -0.77459667  0.26306757  0.12381479]
 [ 1.         -0.37796447 -0.77459667 -0.25350148  0.46175632]
 [-1.         -0.37796447  1.29099445 -1.97539832 -1.53093341]
 [-1.         -0.37796447  1.29099445  0.05261351 -1.11141978]
 [ 1.         -0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [-1.         -0.37796447  1.29099445 -0.0813118  -0.16751412]
 [ 1.         -0.37796447 -0.77459667  0.95182631  0.98614835]
 [ 1.         -0.37796447 -0.77459667 -0.59788085 -0.48214934]]


In [17]:
X_test = sc_X.transform(X_test)
print(X_test)

[[-1.          2.64575131 -0.77459667 -1.45882927 -0.90166297]
 [-1.          2.64575131 -0.77459667  1.98496442  2.13981082]]
